# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
    -   id: clang-format
        types_or: [c++, c]
-   repo: local
    hooks:
    -   id: generate-dev_requirements.txt
        name: Generate dev_requirements.txt
        entry: make generate-dev-requirements
        language: system
        pass_filenames: false
        always_run: true
